import "./polyfill";
import { Conversation } from "./scopes/conversational/Conversation";
import {
  AttachedVolatileKnowledgeRes,
  ChatWidgetRes,
  ConnectorStatusResult,
  ConversationInfoResult,
  ConversationRes,
  GetConnectorStatusOptions,
  Message,
  RemoveFeedbackOptions,
  RemoveFeedbackResult,
  SubmitFeedbackOptions,
  SubmitFeedbackResult,
} from "./scopes/conversational/Conversation/types";
import { RealtimeSession } from "./scopes/conversational/RealtimeSession";
import type {
  RealtimeErrorDetails,
  RealtimeErrorSource,
  SerenitySessionCloseReason,
} from "./scopes/conversational/RealtimeSession/types";
import { SerenityClient, FullSerenityClient, ScopedSerenityClient } from "./SerenityClient";
import type { FullAgents, FullServices, ScopedAgents } from "./SerenityClient";
import {
  AgentResult,
  CitationRes,
  CitationSource,
  BaseErrorBody,
  FileError,
  PendingAction,
  ConnectionPendingAction,
  ToolApprovalPendingAction,
  ToolApprovalDecision,
  UserChoicePendingAction,
  UserChoiceQuestion,
  UserChoiceOption,
  UserChoiceAnswer,
  RateLimitErrorBody,
  ValidationErrorBody,
  AgentExecutionFailedErrorBody,
  AIServiceExecutionFailedErrorBody,
  AttemptErrorCode,
  BusinessValidationErrorBody,
  ErrorDetails,
  ExecutionAttempt,
  NotFoundErrorBody,
  NotFoundErrorKey,
  SerenityErrorBody,
  SerenityErrorCode,
  StreamErrorEvent,
  StreamExecutionAttempt,
  ValidationErrorKey,
  VendorAttemptCode,
  VendorFaultCode,
  VolatileKnowledgeExpirationOptions,
  VolatileKnowledgeProcessingOptions,
  VolatileKnowledgeUploadFromBase64Options,
  VolatileKnowledgeUploadFromFileIdOptions,
  VolatileKnowledgeUploadFromUrlOptions,
  VolatileKnowledgeUploadOptions,
  VolatileKnowledgeUploadRes,
  TranscribeAudioOptions,
  TranscribeAudioResult,
  FileUploadRes,
  TokenProviderFn,
  TokenProviderContext,
  AgentClientCredentials,
} from "./types";
import { ExternalErrorHelper } from "./utils/ErrorHelper";
import type { SerenityErrorType } from "./utils/ErrorHelper";
import { VolatileKnowledgeManager } from "./utils/VolatileKnowledgeManager";
import { AuthProvider } from "./auth/AuthProvider";
import { SerenityApiError } from "./errors";
import { VENDOR_FAULT_CODES } from "./types";

export {
  SerenityClient,
  FullSerenityClient,
  ScopedSerenityClient,
  RealtimeSession,
  ExternalErrorHelper as ErrorHelper,
  VolatileKnowledgeManager,
  SerenityApiError,
  VENDOR_FAULT_CODES,
};
export type {
  AgentResult,
  CitationRes,
  CitationSource,
  ConversationRes,
  ConversationInfoResult,
  ChatWidgetRes,
  BaseErrorBody,
  RateLimitErrorBody,
  ValidationErrorBody,
  BusinessValidationErrorBody,
  NotFoundErrorBody,
  AgentExecutionFailedErrorBody,
  AIServiceExecutionFailedErrorBody,
  ExecutionAttempt,
  SerenityErrorBody,
  SerenityErrorCode,
  SerenityErrorType,
  AttemptErrorCode,
  VendorAttemptCode,
  VendorFaultCode,
  NotFoundErrorKey,
  ValidationErrorKey,
  ErrorDetails,
  StreamErrorEvent,
  StreamExecutionAttempt,
  SerenitySessionCloseReason,
  RealtimeErrorDetails,
  RealtimeErrorSource,
  Conversation,
  Message,
  SubmitFeedbackOptions,
  SubmitFeedbackResult,
  RemoveFeedbackOptions,
  RemoveFeedbackResult,
  GetConnectorStatusOptions,
  ConnectorStatusResult,
  PendingAction,
  ConnectionPendingAction,
  ToolApprovalPendingAction,
  ToolApprovalDecision,
  UserChoicePendingAction,
  UserChoiceQuestion,
  UserChoiceOption,
  UserChoiceAnswer,
  VolatileKnowledgeExpirationOptions,
  VolatileKnowledgeProcessingOptions,
  VolatileKnowledgeUploadFromBase64Options,
  VolatileKnowledgeUploadFromFileIdOptions,
  VolatileKnowledgeUploadFromUrlOptions,
  VolatileKnowledgeUploadOptions,
  VolatileKnowledgeUploadRes,
  FileError,
  TranscribeAudioOptions,
  TranscribeAudioResult,
  FileUploadRes,
  AttachedVolatileKnowledgeRes,
  TokenProviderFn,
  TokenProviderContext,
  AgentClientCredentials,
  AuthProvider,
  FullAgents,
  FullServices,
  ScopedAgents,
};
